### ISSUE TITLE
zh-CN/docs/tensorflow/fec4eaabda2665d4e6fb85c7288f0cb4e66f0aa9/a2

### ISSUE THREAD

**Issue by MonkeyTB** [runebookdev/runebook#428]
> tf.compat.v1.train.Saver
Traceback (most recent call last):
  File "train_help.py", line 43, in <module>
    saver = tf.compat.v1.train.Saver()
  File "/home/jovyan/.conda/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/jovyan/.conda/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/jovyan/.conda/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 865, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
Exception ignored in: <function _RandomSeedGeneratorDeleter.__del__ at 0x7fb758ac6dd0>
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3462, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
tf.compat.v1.train.Saver
I want to know why error,thanks for you help.

**Comment by runebookdev** [comment]
thanks!
